name: Feature Branch CI

on:
  push:
    branches-ignore:
      - 'main'
      - 'staging'
#   pull_request:
#     branches-ignore:
#       - 'main'
#       - 'staging'



jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          
      - name: Install SDL2
        run: |
          sudo apt-get update
          sudo apt-get install -y libsdl2-dev

      - name: Build
        run: cargo build --verbose

      - name: Run Tests
        run: cargo test --verbose

