name: Staging CI

on:
  push:
    branches:
      - 'staging'
  pull_request:
    branches:
      - 'staging'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build
        run: cargo build --verbose

      - name: Run Tests
        run: cargo test --verbose

  clippy:
    runs-on: ubuntu-latest
    needs: build-and-test
    continue-on-error: true

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run Clippy
        run: cargo clippy -- -D warnings

